### ISSUE TITLE
album_groups is expected to be dict but appears as list

### ISSUE THREAD

**Issue by okjuan** [okjuan/music-lib-bot#3]
So far, has only surfaced when grouping 2 albums. It looks like an edge case.

I think it happens when:
```python
if len(album_ids) == 0 or len(matches) == 0:
```

Ouput:
```
Fetching recently saved albums...
Fetched 566 albums...
Grouping 2 albums...
Traceback (most recent call last):
  File "music_lib_bot.py", line 183, in <module>
    make_playlists_from_recently_added_albums()
  File "music_lib_bot.py", line 176, in make_playlists_from_recently_added_albums
    add_albums_to_playlist([
  File "music_lib_bot.py", line 36, in add_albums_to_playlist
    albums_by_genre = group_albums_by_genre(all_albums)
  File "music_lib_bot.py", line 68, in group_albums_by_genre
    for description, group in album_groups.items()
AttributeError: 'list' object has no attribute 'items'
```

**Comment by okjuan** [comment]
Outdated/fixed
